use std::{fs, path::Path};

#[test]
fn signal_inbox_contract_includes_discord_alert_decision_fields() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let source = fs::read_to_string(root.join("src/api/toxic_signal_inbox_routes.rs"))
        .expect("inbox source");

    assert!(source.contains("\"alertStatus\""));
    assert!(source.contains("\"alertReason\""));
    assert!(source.contains("\"discordAlert\""));
    assert!(source.contains("\"riskSystems\""));
    assert!(source.contains("\"toxicShortScore\""));
    assert!(source.contains("\"toxicScore\""));
    assert!(source.contains("\"shortPressure\""));
    assert!(source.contains("\"toxicSeverity\""));
    assert!(source.contains("\"toxicType\""));
    assert!(source.contains("\"toxicTtlSec\""));
    assert!(source.contains("\"toxicExpiresAt\""));
    assert!(source.contains("\"toxicHalfLifeSec\""));
    assert!(source.contains("\"toxicMaxTtlSec\""));
    assert!(source.contains("\"toxicDecayedScore\""));
    assert!(source.contains("\"toxicDecayFormula\""));
    assert!(source.contains("\"toxicReasons\""));
    assert!(source.contains("\"marketStructureScore\""));
    assert!(source.contains("\"mainForceScore\""));
    assert!(source.contains("\"structureBias\""));
    assert!(source.contains("\"extremeImpactScore\""));
    assert!(source.contains("\"regimeType\""));
    assert!(source.contains("\"marketStructureSeverity\""));
    assert!(source.contains("\"marketStructureDataQuality\""));
    assert!(source.contains("\"structureRaw\""));
    assert!(source.contains("\"spotContractFloor\""));
    assert!(source.contains("\"durationScore\""));
    assert!(source.contains("\"liquidationPenalty\""));
    assert!(source.contains("\"crowdingPenalty\""));
    assert!(source.contains("\"spotScore\""));
    assert!(source.contains("\"spotCvdScore\""));
    assert!(source.contains("\"spotVolumeAnomaly\""));
    assert!(source.contains("\"spotAbsorption\""));
    assert!(source.contains("\"spotLiquidityShift\""));
    assert!(source.contains("\"spotPriceResponse\""));
    assert!(source.contains("\"contractScore\""));
    assert!(source.contains("\"cwmAggressiveFlow\""));
    assert!(source.contains("\"oiImpulse\""));
    assert!(source.contains("\"liquidationContext\""));
    assert!(source.contains("\"fundingCrowding\""));
    assert!(source.contains("\"basisPremium\""));
    assert!(source.contains("\"activeExchangeConfirmation\""));
    assert!(source.contains("\"crossConfirmScore\""));
    assert!(source.contains("\"oiScore\""));
    assert!(source.contains("\"liquidationScore\""));
    assert!(source.contains("\"fundingCrowdingScore\""));
    assert!(source.contains("\"cwmScore\""));
    assert!(source.contains("\"marketStructureReasons\""));
    assert!(source.contains("\"finalRiskScore\""));
    assert!(source.contains("\"riskScore\""));
    assert!(source.contains("\"perpTofMetrics\""));
    assert!(source.contains("\"perpScore\""));
    assert!(source.contains("\"perpCandidateType\""));
    assert!(source.contains("\"finalCandidateType\""));
    assert!(source.contains("\"metricsDirection\""));
    assert!(source.contains("\"advancedTofMetrics\""));
    assert!(source.contains("\"advancedScore\""));
    assert!(source.contains("\"advancedCandidateType\""));
    assert!(source.contains("\"cwmContribution\""));
    assert!(source.contains("evaluate_discord_alert_gate"));
    assert!(source.contains("build_perp_tof_metrics"));
    assert!(source.contains("build_advanced_tof_metrics"));
    assert!(source.contains("build_cwm_risk_contribution"));
    assert!(source.contains("build_split_risk_systems"));
    assert!(!source.contains("fused_risk_score_with_cwm"));
    assert!(source.contains("latest_cwm_signal_for_state"));
}
