use std::net::SocketAddr;

use anyhow::Context;
use axum::{middleware, routing::get, Router};

use crate::{
    api::{
        active_trade_toxicity_routes, calibration_routes, durable_archive_dryrun_routes,
        durable_archive_write_audit_routes, durable_archive_write_routes,
        liquidation_toxicity_routes, manual_apply_dryrun_routes, manual_apply_evidence_pack_routes,
        manual_apply_governance_routes, manual_apply_runbook_routes, manual_audit_story_routes,
        manual_evidence_freshness_routes, manual_governance_index_routes,
        manual_parameter_export_routes, manual_signoff_routes, manual_startup_routes,
        orderbook_wall_interpretation_routes, orderbook_wall_lifecycle_routes,
        parameter_patch_diff_routes, parameter_review_routes, routes, runtime_control_routes,
        security, static_files, structural_toxicity_routes, toxic_governance_ledger_routes,
        toxic_governance_proposal_routes, toxic_governance_review_pack_routes,
        toxic_governance_signoff_pack_routes, toxic_markout_routes, toxic_quality_scorecard_routes,
        toxic_replay_routes, toxic_signal_alert_preview_routes, toxic_signal_detail_routes,
        toxic_signal_group_routes, toxic_signal_health_routes, toxic_signal_history_routes,
        toxic_signal_inbox_routes, toxic_signal_report_routes, toxic_signal_routes,
        toxic_weight_recommendation_routes, toxic_weight_review_routes,
        whale_flow_calibration_routes, whale_flow_candidate_history_routes, whale_flow_routes,
    },
    app::AppState,
    config::AppConfig,
};

pub fn router(state: AppState) -> Router {
    let security_config = security::ApiSecurityConfig::from_app_config(state.config());
    Router::new()
        .route("/", get(static_files::root))
        .route("/dashboard", get(static_files::dashboard))
        .route("/web/app.js", get(static_files::app_js))
        .route("/web/styles.css", get(static_files::styles_css))
        .route("/api/status", get(routes::status))
        .route("/api/venues/diagnostics", get(routes::venues_diagnostics))
        .route(
            "/api/runtime/start",
            axum::routing::post(runtime_control_routes::ensure_monitoring_started),
        )
        .route(
            "/api/runtime/stop",
            axum::routing::post(runtime_control_routes::ensure_monitoring_stopped),
        )
        .route(
            "/api/archive/dry-run/write",
            axum::routing::post(durable_archive_dryrun_routes::durable_archive_dryrun_write_route),
        )
        .route(
            "/api/archive/dry-run/review-pack/latest",
            get(durable_archive_dryrun_routes::durable_archive_dryrun_review_pack_latest_route),
        )
        .route(
            "/api/archive/dry-run/review-pack/:dry_run_id",
            get(durable_archive_dryrun_routes::durable_archive_dryrun_review_pack_by_id_route),
        )
        .route(
            "/api/archive/write/status",
            get(durable_archive_write_routes::durable_archive_write_status_route),
        )
        .route(
            "/api/archive/write/audit/status",
            get(durable_archive_write_audit_routes::durable_archive_write_audit_status_route),
        )
        .route(
            "/api/archive/write/audit/recent",
            get(durable_archive_write_audit_routes::durable_archive_write_audit_recent_route),
        )
        .route(
            "/api/archive/write/audit/latest",
            get(durable_archive_write_audit_routes::durable_archive_write_audit_latest_route),
        )
        .route(
            "/api/archive/write",
            axum::routing::post(durable_archive_write_routes::durable_archive_write_route),
        )
        .route("/api/flow-state", get(routes::flow_state))
        .route("/api/markout-state", get(routes::markout_state))
        .route("/api/sweep-state", get(routes::sweep_state))
        .route("/api/liquidation-state", get(routes::liquidation_state))
        .route(
            "/api/toxicity/liquidation/status",
            get(liquidation_toxicity_routes::liquidation_toxicity_status),
        )
        .route(
            "/api/toxicity/liquidation/recent",
            get(liquidation_toxicity_routes::liquidation_toxicity_recent),
        )
        .route(
            "/api/toxicity/orderbook-walls/status",
            get(orderbook_wall_lifecycle_routes::orderbook_wall_lifecycle_status),
        )
        .route(
            "/api/toxicity/orderbook-walls/recent",
            get(orderbook_wall_lifecycle_routes::orderbook_wall_lifecycle_recent),
        )
        .route(
            "/api/toxicity/orderbook-walls/:symbol",
            get(orderbook_wall_lifecycle_routes::orderbook_wall_lifecycle_for_symbol),
        )
        .route(
            "/api/toxicity/orderbook-wall-interpretation/status",
            get(orderbook_wall_interpretation_routes::orderbook_wall_interpretation_status),
        )
        .route(
            "/api/toxicity/orderbook-wall-interpretation/recent",
            get(orderbook_wall_interpretation_routes::orderbook_wall_interpretation_recent),
        )
        .route(
            "/api/toxicity/orderbook-wall-interpretation/:symbol",
            get(orderbook_wall_interpretation_routes::orderbook_wall_interpretation_for_symbol),
        )
        .route(
            "/api/toxicity/structural/status",
            get(structural_toxicity_routes::structural_toxicity_status),
        )
        .route(
            "/api/toxicity/structural/recent",
            get(structural_toxicity_routes::structural_toxicity_recent),
        )
        .route(
            "/api/toxicity/structural/:symbol",
            get(structural_toxicity_routes::structural_toxicity_for_symbol),
        )
        .route(
            "/api/toxicity/whale-flow/status",
            get(whale_flow_routes::whale_flow_status),
        )
        .route(
            "/api/toxicity/whale-flow/recent",
            get(whale_flow_routes::whale_flow_recent),
        )
        .route(
            "/api/toxicity/whale-flow/calibration/status",
            get(whale_flow_calibration_routes::whale_flow_calibration_status),
        )
        .route(
            "/api/toxicity/whale-flow/calibration/report",
            get(whale_flow_calibration_routes::whale_flow_calibration_report),
        )
        .route(
            "/api/toxicity/whale-flow/calibration/:symbol",
            get(whale_flow_calibration_routes::whale_flow_calibration_for_symbol),
        )
        .route(
            "/api/toxicity/whale-flow/history/status",
            get(whale_flow_candidate_history_routes::whale_flow_candidate_history_status),
        )
        .route(
            "/api/toxicity/whale-flow/history/recent",
            get(whale_flow_candidate_history_routes::whale_flow_candidate_history_recent),
        )
        .route(
            "/api/toxicity/whale-flow/history/:symbol",
            get(whale_flow_candidate_history_routes::whale_flow_candidate_history_for_symbol),
        )
        .route(
            "/api/toxicity/whale-flow/:symbol",
            get(whale_flow_routes::whale_flow_for_symbol),
        )
        .route(
            "/api/toxicity/fusion/status",
            get(toxic_signal_routes::toxic_signal_fusion_status),
        )
        .route(
            "/api/toxicity/fusion/recent",
            get(toxic_signal_routes::toxic_signal_fusion_recent),
        )
        .route(
            "/api/toxicity/fusion/:symbol",
            get(toxic_signal_routes::toxic_signal_fusion_for_symbol),
        )
        .route(
            "/api/toxicity/signal-inbox/status",
            get(toxic_signal_inbox_routes::toxic_signal_inbox_status_route),
        )
        .route(
            "/api/toxicity/signal-inbox/recent",
            get(toxic_signal_inbox_routes::toxic_signal_inbox_recent_route),
        )
        .route(
            "/api/toxicity/signal-inbox/signal/:signal_id",
            get(toxic_signal_inbox_routes::toxic_signal_inbox_for_signal),
        )
        .route(
            "/api/toxicity/signal-inbox/:symbol",
            get(toxic_signal_inbox_routes::toxic_signal_inbox_for_symbol),
        )
        .route(
            "/api/toxicity/signal-groups/status",
            get(toxic_signal_group_routes::toxic_signal_group_status_route),
        )
        .route(
            "/api/toxicity/signal-groups/recent",
            get(toxic_signal_group_routes::toxic_signal_group_recent_route),
        )
        .route(
            "/api/toxicity/signal-groups/group/:group_id",
            get(toxic_signal_group_routes::toxic_signal_group_detail_route),
        )
        .route(
            "/api/toxicity/signal-groups/:symbol",
            get(toxic_signal_group_routes::toxic_signal_group_for_symbol),
        )
        .route(
            "/api/toxicity/signal-detail/status",
            get(toxic_signal_detail_routes::toxic_signal_detail_status_route),
        )
        .route(
            "/api/toxicity/signal-detail/group/:group_id",
            get(toxic_signal_detail_routes::toxic_signal_detail_for_group),
        )
        .route(
            "/api/toxicity/signal-detail/:signal_id",
            get(toxic_signal_detail_routes::toxic_signal_detail_for_signal),
        )
        .route(
            "/api/toxicity/signal-health/status",
            get(toxic_signal_health_routes::toxic_signal_health_status_route),
        )
        .route(
            "/api/toxicity/signal-health/summary",
            get(toxic_signal_health_routes::toxic_signal_health_summary_route),
        )
        .route(
            "/api/toxicity/signal-health/:symbol",
            get(toxic_signal_health_routes::toxic_signal_health_for_symbol),
        )
        .route(
            "/api/toxicity/signal-history/status",
            get(toxic_signal_history_routes::toxic_signal_history_status_route),
        )
        .route(
            "/api/toxicity/signal-history/recent",
            get(toxic_signal_history_routes::toxic_signal_history_recent_route),
        )
        .route(
            "/api/toxicity/signal-history/signal/:signal_id",
            get(toxic_signal_history_routes::toxic_signal_history_signal_route),
        )
        .route(
            "/api/toxicity/signal-history/alerts/recent",
            get(toxic_signal_history_routes::toxic_signal_history_alert_recent_route),
        )
        .route(
            "/api/toxicity/signal-history/reports/recent",
            get(toxic_signal_history_routes::toxic_signal_history_report_recent_route),
        )
        .route(
            "/api/toxicity/signal-history/:symbol",
            get(toxic_signal_history_routes::toxic_signal_history_for_symbol),
        )
        .route(
            "/api/toxicity/signal-report/status",
            get(toxic_signal_report_routes::toxic_signal_report_status_route),
        )
        .route(
            "/api/toxicity/signal-report/daily",
            get(toxic_signal_report_routes::toxic_signal_report_daily_route),
        )
        .route(
            "/api/toxicity/signal-report/rolling",
            get(toxic_signal_report_routes::toxic_signal_report_rolling_route),
        )
        .route(
            "/api/toxicity/signal-alert-preview/status",
            get(toxic_signal_alert_preview_routes::toxic_signal_alert_preview_status_route),
        )
        .route(
            "/api/toxicity/signal-alert-preview/explain/:signal_id",
            get(toxic_signal_alert_preview_routes::toxic_signal_alert_preview_explain_route),
        )
        .route(
            "/api/toxicity/signal-alert-preview/recent",
            get(toxic_signal_alert_preview_routes::toxic_signal_alert_preview_recent_route),
        )
        .route(
            "/api/toxicity/replay/status",
            get(toxic_replay_routes::toxic_replay_status),
        )
        .route(
            "/api/toxicity/replay/recent",
            get(toxic_replay_routes::toxic_replay_recent),
        )
        .route(
            "/api/toxicity/replay/:symbol/latest",
            get(toxic_replay_routes::toxic_replay_latest_for_symbol),
        )
        .route(
            "/api/toxicity/replay/:symbol/:signal_id",
            get(toxic_replay_routes::toxic_replay_signal_for_symbol),
        )
        .route(
            "/api/toxicity/replay/:symbol",
            get(toxic_replay_routes::toxic_replay_for_symbol),
        )
        .route(
            "/api/toxicity/markout/status",
            get(toxic_markout_routes::toxic_markout_status_route),
        )
        .route(
            "/api/toxicity/markout/recent",
            get(toxic_markout_routes::toxic_markout_recent_route),
        )
        .route(
            "/api/toxicity/markout/signal/:signal_id",
            get(toxic_markout_routes::toxic_markout_for_signal),
        )
        .route(
            "/api/toxicity/markout/:symbol",
            get(toxic_markout_routes::toxic_markout_for_symbol),
        )
        .route(
            "/api/toxicity/quality-scorecard/status",
            get(toxic_quality_scorecard_routes::toxic_quality_scorecard_status_route),
        )
        .route(
            "/api/toxicity/quality-scorecard/summary",
            get(toxic_quality_scorecard_routes::toxic_quality_scorecard_summary_route),
        )
        .route(
            "/api/toxicity/quality-scorecard/:symbol",
            get(toxic_quality_scorecard_routes::toxic_quality_scorecard_for_symbol),
        )
        .route(
            "/api/toxicity/weight-recommendation/status",
            get(toxic_weight_recommendation_routes::toxic_weight_recommendation_status_route),
        )
        .route(
            "/api/toxicity/weight-recommendation/summary",
            get(toxic_weight_recommendation_routes::toxic_weight_recommendation_summary_route),
        )
        .route(
            "/api/toxicity/weight-recommendation/:symbol",
            get(toxic_weight_recommendation_routes::toxic_weight_recommendation_for_symbol),
        )
        .route(
            "/api/toxicity/weight-review/status",
            get(toxic_weight_review_routes::toxic_weight_review_status_route),
        )
        .route(
            "/api/toxicity/weight-review/summary",
            get(toxic_weight_review_routes::toxic_weight_review_summary_route),
        )
        .route(
            "/api/toxicity/weight-review/latest",
            get(toxic_weight_review_routes::toxic_weight_review_latest_route),
        )
        .route(
            "/api/toxicity/weight-review/export",
            get(toxic_weight_review_routes::toxic_weight_review_export_route),
        )
        .route(
            "/api/toxicity/weight-review/:symbol/export",
            get(toxic_weight_review_routes::toxic_weight_review_export_for_symbol),
        )
        .route(
            "/api/toxicity/weight-review/:symbol",
            get(toxic_weight_review_routes::toxic_weight_review_for_symbol),
        )
        .route(
            "/api/toxicity/governance-ledger/status",
            get(toxic_governance_ledger_routes::toxic_governance_ledger_status_route),
        )
        .route(
            "/api/toxicity/governance-ledger/summary",
            get(toxic_governance_ledger_routes::toxic_governance_ledger_summary_route),
        )
        .route(
            "/api/toxicity/governance-ledger/recent",
            get(toxic_governance_ledger_routes::toxic_governance_ledger_recent_route),
        )
        .route(
            "/api/toxicity/governance-ledger/export",
            get(toxic_governance_ledger_routes::toxic_governance_ledger_export_route),
        )
        .route(
            "/api/toxicity/governance-ledger/:symbol",
            get(toxic_governance_ledger_routes::toxic_governance_ledger_for_symbol),
        )
        .route(
            "/api/toxicity/governance-proposal/status",
            get(toxic_governance_proposal_routes::toxic_governance_proposal_status_route),
        )
        .route(
            "/api/toxicity/governance-proposal/summary",
            get(toxic_governance_proposal_routes::toxic_governance_proposal_summary_route),
        )
        .route(
            "/api/toxicity/governance-proposal/export",
            get(toxic_governance_proposal_routes::toxic_governance_proposal_export_route),
        )
        .route(
            "/api/toxicity/governance-proposal/:symbol",
            get(toxic_governance_proposal_routes::toxic_governance_proposal_for_symbol),
        )
        .route(
            "/api/toxicity/governance-review-pack/status",
            get(toxic_governance_review_pack_routes::toxic_governance_review_pack_status_route),
        )
        .route(
            "/api/toxicity/governance-review-pack/summary",
            get(toxic_governance_review_pack_routes::toxic_governance_review_pack_summary_route),
        )
        .route(
            "/api/toxicity/governance-review-pack/export",
            get(toxic_governance_review_pack_routes::toxic_governance_review_pack_export_route),
        )
        .route(
            "/api/toxicity/governance-review-pack/:symbol",
            get(toxic_governance_review_pack_routes::toxic_governance_review_pack_for_symbol),
        )
        .route(
            "/api/toxicity/governance-signoff-pack/status",
            get(toxic_governance_signoff_pack_routes::toxic_governance_signoff_pack_status_route),
        )
        .route(
            "/api/toxicity/governance-signoff-pack/summary",
            get(toxic_governance_signoff_pack_routes::toxic_governance_signoff_pack_summary_route),
        )
        .route(
            "/api/toxicity/governance-signoff-pack/export",
            get(toxic_governance_signoff_pack_routes::toxic_governance_signoff_pack_export_route),
        )
        .route(
            "/api/toxicity/governance-signoff-pack/:symbol",
            get(toxic_governance_signoff_pack_routes::toxic_governance_signoff_pack_for_symbol),
        )
        .route("/api/liq-hunt-state", get(routes::liq_hunt_state))
        .route("/api/vpin-state", get(routes::vpin_state))
        .route("/api/vpin-buckets", get(routes::vpin_buckets))
        .route("/api/toxic-state", get(routes::toxic_state))
        .route(
            "/api/toxicity/active-trade/status",
            get(active_trade_toxicity_routes::active_trade_toxicity_status),
        )
        .route(
            "/api/toxicity/active-trade/recent",
            get(active_trade_toxicity_routes::active_trade_toxicity_recent),
        )
        .route(
            "/api/toxicity/active-trades",
            get(active_trade_toxicity_routes::active_trade_toxicity),
        )
        .route(
            "/api/toxicity/active-trades/:symbol",
            get(active_trade_toxicity_routes::active_trade_toxicity_for_symbol),
        )
        .route("/api/toxic-events", get(routes::toxic_events))
        .route("/api/toxic-events/latest", get(routes::latest_toxic_event))
        .route("/api/replay-reports", get(routes::replay_reports))
        .route(
            "/api/calibration/reports",
            get(calibration_routes::calibration_reports),
        )
        .route(
            "/api/calibration/reports/latest",
            get(calibration_routes::latest_calibration_report),
        )
        .route(
            "/api/calibration/reports/:report_id",
            get(calibration_routes::calibration_report_by_id),
        )
        .route(
            "/api/calibration/manual-startup/check",
            get(manual_startup_routes::manual_startup_check),
        )
        .route(
            "/api/calibration/manual-signoff/status",
            get(manual_signoff_routes::manual_signoff_status),
        )
        .route(
            "/api/calibration/manual-signoff",
            axum::routing::post(manual_signoff_routes::create_manual_signoff),
        )
        .route(
            "/api/calibration/manual-signoff/history",
            get(manual_signoff_routes::manual_signoff_history),
        )
        .route(
            "/api/calibration/manual-evidence/freshness",
            get(manual_evidence_freshness_routes::manual_evidence_freshness),
        )
        .route(
            "/api/calibration/manual-audit-story",
            get(manual_audit_story_routes::manual_audit_story),
        )
        .route(
            "/api/calibration/manual-audit-story.md",
            get(manual_audit_story_routes::manual_audit_story_markdown),
        )
        .route(
            "/api/calibration/manual-governance/index",
            get(manual_governance_index_routes::manual_governance_index),
        )
        .route(
            "/api/parameter-review/governance",
            get(manual_apply_governance_routes::manual_apply_governance),
        )
        .route(
            "/api/parameter-review/governance/latest",
            get(manual_apply_governance_routes::latest_manual_apply_governance),
        )
        .route(
            "/api/parameter-review/governance.md",
            get(manual_apply_governance_routes::manual_apply_governance_markdown),
        )
        .route(
            "/api/parameter-review/recommendations",
            get(parameter_review_routes::parameter_recommendations),
        )
        .route(
            "/api/parameter-review/recommendations/latest",
            get(parameter_review_routes::latest_parameter_recommendations),
        )
        .route(
            "/api/parameter-review/recommendations/:recommendation_id",
            get(parameter_review_routes::parameter_recommendation_by_id),
        )
        .route(
            "/api/parameter-review/reviews",
            get(parameter_review_routes::parameter_reviews)
                .post(parameter_review_routes::create_parameter_review),
        )
        .route(
            "/api/parameter-review/exports",
            get(manual_parameter_export_routes::parameter_exports)
                .post(manual_parameter_export_routes::create_parameter_export),
        )
        .route(
            "/api/parameter-review/exports/latest",
            get(manual_parameter_export_routes::latest_parameter_export),
        )
        .route(
            "/api/parameter-review/exports/latest/diff",
            get(parameter_patch_diff_routes::latest_parameter_export_diff),
        )
        .route(
            "/api/parameter-review/exports/latest/audit",
            get(parameter_patch_diff_routes::latest_parameter_export_audit),
        )
        .route(
            "/api/parameter-review/exports/latest/runbook",
            get(manual_apply_runbook_routes::latest_manual_apply_runbook),
        )
        .route(
            "/api/parameter-review/exports/latest/runbook.md",
            get(manual_apply_runbook_routes::latest_manual_apply_runbook_markdown),
        )
        .route(
            "/api/parameter-review/exports/latest/dry-run",
            get(manual_apply_dryrun_routes::latest_manual_apply_dry_run),
        )
        .route(
            "/api/parameter-review/exports/latest/dry-run.md",
            get(manual_apply_dryrun_routes::latest_manual_apply_dry_run_markdown),
        )
        .route(
            "/api/parameter-review/exports/latest/evidence-pack",
            get(manual_apply_evidence_pack_routes::latest_manual_apply_evidence_pack),
        )
        .route(
            "/api/parameter-review/exports/latest/evidence-pack.md",
            get(manual_apply_evidence_pack_routes::latest_manual_apply_evidence_pack_markdown),
        )
        .route(
            "/api/parameter-review/exports/:export_id",
            get(manual_parameter_export_routes::parameter_export_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/diff",
            get(parameter_patch_diff_routes::parameter_export_diff_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/audit",
            get(parameter_patch_diff_routes::parameter_export_audit_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/runbook",
            get(manual_apply_runbook_routes::manual_apply_runbook_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/runbook.md",
            get(manual_apply_runbook_routes::manual_apply_runbook_markdown_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/dry-run",
            get(manual_apply_dryrun_routes::manual_apply_dry_run_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/dry-run.md",
            get(manual_apply_dryrun_routes::manual_apply_dry_run_markdown_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/evidence-pack",
            get(manual_apply_evidence_pack_routes::manual_apply_evidence_pack_by_id),
        )
        .route(
            "/api/parameter-review/exports/:export_id/evidence-pack.md",
            get(manual_apply_evidence_pack_routes::manual_apply_evidence_pack_markdown_by_id),
        )
        .route(
            "/api/replay-reports/:file_name",
            get(routes::replay_report_content),
        )
        .route("/api/storage/status", get(routes::storage_status))
        .layer(middleware::from_fn_with_state(
            security_config.clone(),
            security::guard_operator_post_requests,
        ))
        .layer(security_config.cors_layer())
        .with_state(state)
}

pub async fn serve(config: AppConfig, state: AppState) -> anyhow::Result<()> {
    let addr = SocketAddr::new(config.api_host, config.api_port);
    let listener = tokio::net::TcpListener::bind(addr)
        .await
        .with_context(|| format!("failed to bind {addr}"))?;
    tracing::info!("btc-toxic-flow-monitor-rs listening on http://{addr}");
    axum::serve(listener, router(state))
        .await
        .context("api server failed")
}
